/* Canonical transaction-bearing investor records: types and derivation.
 *
 * Package 07 (B5): the canonical store for investor data is transaction-
 * bearing (per holding: provenance labels, quantity, cost basis, dates,
 * vehicle attributes, and, where eCAS truth exists, the full dated
 * transaction list priced on the real snapshot monthly_nav series). The
 * demo-surface StructuredHoldings shape is a deterministic DERIVATION from
 * these records, and the five demo investors are frozen via a byte-identity
 * invariant: deriveStructuredHoldings(record) must JSON-stringify identically
 * to the hand-authored records in db/fixtures/structured-holdings.ts
 * (asserted by scripts/_verify-holdings-identity.ts and by the fixture
 * builder itself). Agents keep reading the derived shape; nothing in the
 * pipeline changes because this layer exists.
 *
 * Sharma is not in the canonical store (no corpus rows; the persona predates
 * the ingestion corpus) and keeps its hand-authored StructuredHoldings only.
 *
 * Data file: db/fixtures/investor-transactions.ts, generated by
 * scripts/generate-investor-transactions.ts from fixtures/ingestion-corpus/.
 */

import type {
  AssetClass,
  SubCategory,
  StructuredHoldings,
  Holding,
  ExcludedHolding,
} from "./structured-holdings";

export type CanonicalTransaction = {
  /* ISO date of the statement row. */
  date: string;
  /* Statement row type verbatim (SIP Purchase, Purchase-BSE -, Switch-In...,
   * stamp-duty and address rows included for statement fidelity). */
  type: string;
  amountInr: number | null;
  units: number | null;
  nav: number | null;
  unitBalance: number | null;
};

export type CanonicalHolding = {
  /* The frozen demo-surface label, byte-identical to the corresponding
   * db/fixtures/structured-holdings.ts entry. */
  instrument: string;
  /* The ingestion-corpus holdings-row label (provenance; may differ from the
   * frozen label, e.g. pre-cleanup fund names). */
  rawLabel: string;
  assetClass: AssetClass;
  subCategory: SubCategory;
  valueCr: number;
  quantity: number | null;
  costBasisTotalInr: number | null;
  costBasisPerUnitInr: number | null;
  purchaseDate: string | null;
  /* Contractual attributes (FD interest_rate and maturity, bond yield and
   * maturity, gold purity...); the real-data basis for accrual value paths. */
  vehicleAttributes: Record<string, unknown> | null;
  /* Snapshot fund identity where eCAS truth exists (resolved via the shared
   * alias map at generation time). */
  resolvedInstrument: string | null;
  amfiCode: number | null;
  folioNo: string | null;
  /* The month-end grid point the closing units tie to (eCAS holdings). */
  navAnchorMonth: string | null;
  /* The real monthly_nav value at the anchor month (eCAS holdings). */
  closingNav: number | null;
  /* Units at the anchor month per the eCAS truth (eCAS holdings). */
  closingUnits: number | null;
  /* Full dated transaction history (eCAS holdings); null for single-lot
   * holdings whose only dated event is purchaseDate at costBasisTotalInr. */
  transactions: CanonicalTransaction[] | null;
};

export type CanonicalExcludedHolding = {
  instrument: string;
  rawLabel: string;
  subCategory: SubCategory;
  valueCr: number;
  /* The frozen demo-surface note, byte-identical to structured-holdings. */
  note: string;
  purchaseDate: string | null;
  costBasisTotalInr: number | null;
};

export type CanonicalInvestorRecord = {
  /* App investor id (db/seed.ts): malhotra, iyengar, bhatt, menon, surana. */
  investorId: string;
  /* Corpus archetype id (the A1-A5 holdings file key for this investor). */
  archetypeId: string;
  totalLiquidAumCr: number;
  /* Ordered to match the frozen structured-holdings array order. */
  holdings: CanonicalHolding[];
  excludedHoldings: CanonicalExcludedHolding[] | null;
};

function round1(x: number): number {
  return Math.round(x * 10) / 10;
}

/* The freeze derivation. Key order in the emitted objects deliberately
 * mirrors the hand-authored literals so JSON.stringify equality is the
 * byte-identity invariant. */
export function deriveStructuredHoldings(
  rec: CanonicalInvestorRecord,
): StructuredHoldings {
  const holdings: Holding[] = rec.holdings.map((h) => ({
    instrument: h.instrument,
    assetClass: h.assetClass,
    subCategory: h.subCategory,
    valueCr: h.valueCr,
    weightPct: round1((h.valueCr / rec.totalLiquidAumCr) * 100),
  }));
  const derived: StructuredHoldings = {
    totalLiquidAumCr: rec.totalLiquidAumCr,
    holdings,
  };
  if (rec.excludedHoldings && rec.excludedHoldings.length > 0) {
    const excluded: ExcludedHolding[] = rec.excludedHoldings.map((e) => ({
      instrument: e.instrument,
      subCategory: e.subCategory,
      valueCr: e.valueCr,
      note: e.note,
    }));
    derived.excludedHoldings = excluded;
  }
  return derived;
}
