/* Export a case row from the database as a JSON fixture.
 *
 * Usage: npx tsx scripts/export-case-fixture.ts <caseId>
 *
 * Writes to db/fixtures/cases/<caseId>.json. Contains a complete
 * serialization of the Case row sufficient to reconstruct it exactly
 * (id, investorId, snapshotId, workflow, severity, headline, status,
 * frozenAt, content, tokenUsage, errorMessage, contextNote).
 *
 * contentJson and tokenUsageJson are stored as nested objects (parsed)
 * rather than escaped strings, so the fixture is human-readable in
 * version control. The seed re-stringifies them on load.
 *
 * The architectural pattern for Slice 2 and beyond: cases generated by
 * the real reasoning pipeline are expensive ($3+ per case in API spend);
 * they get persisted as fixtures so demo state is reliable and zero-API-
 * cost on `npm run db:seed`. Slice 3's Sharma case follows the same
 * pattern.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { prisma } from "../lib/prisma";

const FIXTURE_DIR = path.resolve(process.cwd(), "db", "fixtures", "cases");

async function main() {
  const caseId = process.argv[2];
  if (!caseId) {
    console.error("usage: export-case-fixture.ts <caseId>");
    process.exit(1);
  }

  const c = await prisma.case.findUnique({ where: { id: caseId } });
  if (!c) throw new Error(`Case not found: ${caseId}`);

  /* Parse the embedded JSON strings into nested objects so the fixture is
   * human-readable in version control. The seed re-stringifies. */
  const content = c.contentJson ? safeParse(c.contentJson, "contentJson") : null;
  const tokenUsage = c.tokenUsageJson ? safeParse(c.tokenUsageJson, "tokenUsageJson") : null;

  const fixture = {
    id: c.id,
    investorId: c.investorId,
    snapshotId: c.snapshotId,
    workflow: c.workflow,
    severity: c.severity,
    headline: c.headline,
    status: c.status,
    frozenAt: c.frozenAt.toISOString(),
    content,
    tokenUsage,
    errorMessage: c.errorMessage,
    contextNote: c.contextNote,
  };

  await fs.mkdir(FIXTURE_DIR, { recursive: true });
  const outPath = path.join(FIXTURE_DIR, `${caseId}.json`);
  const json = JSON.stringify(fixture, null, 2);
  await fs.writeFile(outPath, json, "utf-8");
  console.log(`[export-case-fixture] wrote ${outPath} (${json.length} chars)`);

  await prisma.$disconnect();
}

function safeParse(s: string, field: string): unknown {
  try {
    return JSON.parse(s);
  } catch (err) {
    throw new Error(`Failed to parse ${field}: ${err instanceof Error ? err.message : String(err)}`);
  }
}

main().catch((err) => {
  console.error("[export-case-fixture] error:", err);
  process.exit(1);
});
